name: monsterjump
description: Go wash your hands!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+11

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: 0.14.0
  collection:
  url_launcher: ^5.4.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Firebase
  firebase_core:
  firebase_analytics:
  firebase_crashlytics: ^0.1.3+3
  firebase_performance:
  firebase_admob: ^0.9.0+7
  cloud_firestore:

  # Flame
  flame: ^0.18.1

  # Sensors
  sensors: ">=0.4.1+10 <2.0.0"

  # Device Info
  device_info:

  share:
  wakelock: ^0.1.4

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/bg/background.png
    - assets/images/virus/virus.png
    - assets/images/platform/platform.png
    - assets/images/ui/title.png
    - assets/images/ui/subtitle.png
    - assets/images/ui/game_over.png
    - assets/images/ui/share_button.png
    - assets/images/ui/play_button.png
    - assets/images/ui/try_again.png
    - assets/images/ui/gowashyourhands.png
    - assets/images/tipps/1.png
    - assets/images/tipps/2.png
    - assets/images/tipps/3.png
    - assets/images/tipps/4.png
    - assets/images/tipps/5.png
    - assets/images/tipps/6.png
    - assets/images/tipps/7.png
    - assets/images/tipps/8.png
    - assets/images/tipps/9.png
    - assets/images/tipps/10.png
    - assets/images/tipps/11.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
